# Setup
title:        Zynq IoT Platform
tagline:      Cloud-based IoT platform for Xlinx Zync-based devices
baseurl:      "/zynq-iot-platform"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown