# Dockerfile for oneshot build of an image without shared data except the output image

FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
        sed make binutils build-essential gcc \
        g++ bash patch gzip bzip2 perl tar cpio python \
        unzip rsync file bc wget curl parted kpartx \ 
		mtools dosfstools

ENV BUILDROOT_TAR buildroot.tar.gz
ENV BUILDROOT_DIR buildroot

COPY external-tree external-tree

# Fetch LTS Buildroot package
RUN curl -o $BUILDROOT_TAR https://buildroot.uclibc.org/downloads/buildroot-2017.02.3.tar.gz
RUN mkdir $BUILDROOT_DIR
RUN tar xvf $BUILDROOT_TAR -C $BUILDROOT_DIR --strip-components=1
RUN rm $BUILDROOT_TAR

WORKDIR $BUILDROOT_DIR
RUN make BR2_EXTERNAL="../external-tree" test-agent_defconfig
ENTRYPOINT ["make"]
